name: Build and Deploy to Google App Engine

on:
  push:
    branches:
    - master

env:
  GAE_PROJECT: ${{ secrets.GAE_PROJECT }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '281.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy
      run: |
        gcloud app deploy \
          --project=$GAE_PROJECT